# Generated by Django 4.0.3 on 2022-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_number', models.AutoField(primary_key=True, serialize=False, verbose_name='tenant number')),
                ('tenant_id', models.CharField(max_length=100, verbose_name='tenant id')),
                ('address', models.CharField(max_length=100, verbose_name='tenant address')),
                ('description', models.CharField(max_length=100, verbose_name='tenant description')),
            ],
            options={
                'verbose_name_plural': 'tenants',
            },
        ),
    ]
