# Generated by Django 4.0.3 on 2022-04-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'tenant', 'verbose_name_plural': 'tenants'},
        ),
    ]
